### ISSUE TITLE
此插件在velocity群组服下paper端有问题

### ISSUE THREAD

**Issue by zzzhizhia** [Aimerny/OfflineWhitelistReforged#2]
环境：
Velocity群组服，转发类型modern，
测试服务器（B）在加入群组服时处于第二优先级，
最高优先级服务端（A）为fabric，此服务端为paper，
两个服务端均使用此离线白名单插件。
正版验证关闭。所有玩家均没有A的白名单。
以下是对B的操作：
!!wr on后无论玩家是否在B的白名单中，加入时均显示You are not whitelisted on this server.
!!wr off后所有人均能加入B。

**Comment by Aimerny** [comment]
>[!important]
为方便确认问题，在提交issue时请附加上足够详细的信息。
1. 游戏版本
2. 插件版本
3. 复现操作步骤
4. 操作时服务端日志

**Comment by Aimerny** [comment]
没有足够的信息，先close了
